### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by raphael-batlle** [MIM-TPZ/scraping_data_consumer#4]

**Comment by raphael-batlle** [comment]
![archi-scrapper](https://user-images.githubusercontent.com/35702863/36022996-3a5818fa-0d8b-11e8-8944-d696a5eed2d3.png)

**Comment by FlorianBruniaux** [comment]
@raphael-batlle faudrait upgrade en mettant les méhodes (une fois qu'on aura déterminé --> issue?)

**Comment by PandarkMeow** [comment]
![archi scraper](https://user-images.githubusercontent.com/12800595/36023251-18ab08b0-0d8c-11e8-953e-f9122e4a0446.png)

**Comment by FlorianBruniaux** [comment]
@PandarkMeow c'est mieux avec les "contextes"

**Comment by FlorianBruniaux** [comment]
C'est good on close
